import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Channels that default to the new effect-httpapi server backend. The legacy
// hono backend remains the default for stable (`prod`/`latest`) installs.
const HTTPAPI_DEFAULT_ON_CHANNELS = new Set(["dev", "beta", "local"])

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const MYASSISTANT_EXPERIMENTAL = truthy("MYASSISTANT_EXPERIMENTAL")
const MYASSISTANT_DISABLE_CLAUDE_CODE = truthy("MYASSISTANT_DISABLE_CLAUDE_CODE")
const MYASSISTANT_DISABLE_CLAUDE_CODE_SKILLS =
  MYASSISTANT_DISABLE_CLAUDE_CODE || truthy("MYASSISTANT_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["MYASSISTANT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  MYASSISTANT_AUTO_SHARE: truthy("MYASSISTANT_AUTO_SHARE"),
  MYASSISTANT_AUTO_HEAP_SNAPSHOT: truthy("MYASSISTANT_AUTO_HEAP_SNAPSHOT"),
  MYASSISTANT_GIT_BASH_PATH: process.env["MYASSISTANT_GIT_BASH_PATH"],
  MYASSISTANT_CONFIG: process.env["MYASSISTANT_CONFIG"],
  MYASSISTANT_CONFIG_CONTENT: process.env["MYASSISTANT_CONFIG_CONTENT"],
  MYASSISTANT_DISABLE_AUTOUPDATE: truthy("MYASSISTANT_DISABLE_AUTOUPDATE"),
  MYASSISTANT_ALWAYS_NOTIFY_UPDATE: truthy("MYASSISTANT_ALWAYS_NOTIFY_UPDATE"),
  MYASSISTANT_DISABLE_PRUNE: truthy("MYASSISTANT_DISABLE_PRUNE"),
  MYASSISTANT_DISABLE_TERMINAL_TITLE: truthy("MYASSISTANT_DISABLE_TERMINAL_TITLE"),
  MYASSISTANT_SHOW_TTFD: truthy("MYASSISTANT_SHOW_TTFD"),
  MYASSISTANT_PERMISSION: process.env["MYASSISTANT_PERMISSION"],
  MYASSISTANT_DISABLE_DEFAULT_PLUGINS: truthy("MYASSISTANT_DISABLE_DEFAULT_PLUGINS"),
  MYASSISTANT_DISABLE_LSP_DOWNLOAD: truthy("MYASSISTANT_DISABLE_LSP_DOWNLOAD"),
  MYASSISTANT_ENABLE_EXPERIMENTAL_MODELS: truthy("MYASSISTANT_ENABLE_EXPERIMENTAL_MODELS"),
  MYASSISTANT_DISABLE_AUTOCOMPACT: truthy("MYASSISTANT_DISABLE_AUTOCOMPACT"),
  MYASSISTANT_DISABLE_MODELS_FETCH: truthy("MYASSISTANT_DISABLE_MODELS_FETCH"),
  MYASSISTANT_DISABLE_MOUSE: truthy("MYASSISTANT_DISABLE_MOUSE"),
  MYASSISTANT_DISABLE_CLAUDE_CODE,
  MYASSISTANT_DISABLE_CLAUDE_CODE_PROMPT: MYASSISTANT_DISABLE_CLAUDE_CODE || truthy("MYASSISTANT_DISABLE_CLAUDE_CODE_PROMPT"),
  MYASSISTANT_DISABLE_CLAUDE_CODE_SKILLS,
  MYASSISTANT_DISABLE_EXTERNAL_SKILLS: truthy("MYASSISTANT_DISABLE_EXTERNAL_SKILLS"),
  MYASSISTANT_FAKE_VCS: process.env["MYASSISTANT_FAKE_VCS"],
  MYASSISTANT_SERVER_PASSWORD: process.env["MYASSISTANT_SERVER_PASSWORD"],
  MYASSISTANT_SERVER_USERNAME: process.env["MYASSISTANT_SERVER_USERNAME"],
  MYASSISTANT_ENABLE_QUESTION_TOOL: truthy("MYASSISTANT_ENABLE_QUESTION_TOOL"),

  // Experimental
  MYASSISTANT_EXPERIMENTAL,
  MYASSISTANT_EXPERIMENTAL_FILEWATCHER: Config.boolean("MYASSISTANT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MYASSISTANT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("MYASSISTANT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  MYASSISTANT_EXPERIMENTAL_ICON_DISCOVERY: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_ICON_DISCOVERY"),
  MYASSISTANT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("MYASSISTANT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  MYASSISTANT_ENABLE_EXA: truthy("MYASSISTANT_ENABLE_EXA") || MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_EXA"),
  MYASSISTANT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("MYASSISTANT_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  MYASSISTANT_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("MYASSISTANT_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  MYASSISTANT_EXPERIMENTAL_OXFMT: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_OXFMT"),
  MYASSISTANT_EXPERIMENTAL_LSP_TY: truthy("MYASSISTANT_EXPERIMENTAL_LSP_TY"),
  MYASSISTANT_EXPERIMENTAL_LSP_TOOL: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_LSP_TOOL"),
  MYASSISTANT_EXPERIMENTAL_PLAN_MODE: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_PLAN_MODE"),
  MYASSISTANT_EXPERIMENTAL_MARKDOWN: !falsy("MYASSISTANT_EXPERIMENTAL_MARKDOWN"),
  MYASSISTANT_MODELS_URL: process.env["MYASSISTANT_MODELS_URL"],
  MYASSISTANT_MODELS_PATH: process.env["MYASSISTANT_MODELS_PATH"],
  MYASSISTANT_DISABLE_EMBEDDED_WEB_UI: truthy("MYASSISTANT_DISABLE_EMBEDDED_WEB_UI"),
  MYASSISTANT_DB: process.env["MYASSISTANT_DB"],
  MYASSISTANT_DISABLE_CHANNEL_DB: truthy("MYASSISTANT_DISABLE_CHANNEL_DB"),
  MYASSISTANT_SKIP_MIGRATIONS: truthy("MYASSISTANT_SKIP_MIGRATIONS"),
  MYASSISTANT_STRICT_CONFIG_DEPS: truthy("MYASSISTANT_STRICT_CONFIG_DEPS"),

  MYASSISTANT_WORKSPACE_ID: process.env["MYASSISTANT_WORKSPACE_ID"],
  // Defaults to true on dev/beta/local channels so internal users exercise the
  // new effect-httpapi server backend. Stable (`prod`/`latest`) installs stay
  // on the legacy hono backend until the rollout is complete. An explicit env
  // var ("true"/"1" or "false"/"0") always wins, providing an opt-in for
  // stable users and an escape hatch for dev/beta users.
  MYASSISTANT_EXPERIMENTAL_HTTPAPI:
    truthy("MYASSISTANT_EXPERIMENTAL_HTTPAPI") ||
    (!falsy("MYASSISTANT_EXPERIMENTAL_HTTPAPI") && HTTPAPI_DEFAULT_ON_CHANNELS.has(InstallationChannel)),
  MYASSISTANT_EXPERIMENTAL_WORKSPACES: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_WORKSPACES"),
  MYASSISTANT_EXPERIMENTAL_EVENT_SYSTEM: MYASSISTANT_EXPERIMENTAL || truthy("MYASSISTANT_EXPERIMENTAL_EVENT_SYSTEM"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get MYASSISTANT_DISABLE_PROJECT_CONFIG() {
    return truthy("MYASSISTANT_DISABLE_PROJECT_CONFIG")
  },
  get MYASSISTANT_TUI_CONFIG() {
    return process.env["MYASSISTANT_TUI_CONFIG"]
  },
  get MYASSISTANT_CONFIG_DIR() {
    return process.env["MYASSISTANT_CONFIG_DIR"]
  },
  get MYASSISTANT_PURE() {
    return truthy("MYASSISTANT_PURE")
  },
  get MYASSISTANT_PLUGIN_META_FILE() {
    return process.env["MYASSISTANT_PLUGIN_META_FILE"]
  },
  get MYASSISTANT_CLIENT() {
    return process.env["MYASSISTANT_CLIENT"] ?? "cli"
  },
}
